Class('DemoApp.Widget.Footer', {
    
    isa : 'Symbie.Widget.Container',
    
    use : 'Shotenjin.Joosed.Template',
    
    id : {
        footerPk : null
    },
    
    
    has : {
        slots       : true,
        
        template    : function () {
            return new Shotenjin.Joosed.Template({
                /*tj

                    <div class="footer">Footer</div>

                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '<div class="footer">Footer</div>'
            })
        }
    },

    
    
    after : {
        
        onRender : function () {
            this.el.update(this.template.render())
        }
        
    }
    
})