Class('DemoApp.Widget.Header', {
    
    isa : 'Symbie.Widget.Container',
    
    use : 'DemoApp.Template.Base',
    

    has : {
        slots       : true,
        
        template    : function () {
            return new DemoApp.Template.Base({
                /*tj
                    <div class="header">
                        [%\ this.a('/sample') %]Link to Sample</a> |
                        
                        [%\ this.a('/home') %]Link to Home</a> |
                        
                        [%\ this.a('specialOffer') %]Link to Special Offer separately</a>
                    </div>
                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '<div class="header">\n[%\\ this.a(\'/sample\') %]Link to Sample</a> |\n[%\\ this.a(\'/home\') %]Link to Home</a> |\n[%\\ this.a(\'specialOffer\') %]Link to Special Offer separately</a>\n</div>'
            })
        }
    },

    
    
    after : {
        
        onRender : function () {
            this.el.update(this.template.render())
        }
        
    }
    
})