Class('DemoApp.Widget.NotFound', {
    
    xtype   : 'demoapp-widget-notfound',
    
    isa : 'Symbie.Widget.Container',
    
    use : 'DemoApp.Template.Base',
    
    
    has : {
        slots       : true,
        
        template    : function () {
            return new DemoApp.Template.Base({
                /*tj

                    Sorry, this page is missed

                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : 'Sorry, this page is missed'
            })
        }
    },

    
    
    after : {
        
        onRender : function () {
            this.el.update(this.template.render())
        }
        
    }
    
})