Class('DemoApp.Widget.Footer', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : 'Symbie.Widget',
    
    use : 'DemoApp.Template.Base',
    

    has : {
        slots       : true,
        
        cls         : 'footer',
        
        template    : function () {
            return new DemoApp.Template.Base({
                /*tj
                    <div class="demoapp-footer-background"></div>
                    
                    [%\ this.a('/home') %]Home</a> |
                    
                    [%\ this.a('/sample/AnotherValue') %]Another Sample</a> |
                    
                    [%\ this.a('specialOffer') %]Special Offer</a>
                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '<div class="demoapp-footer-background"></div>\n[%\\ this.a(\'/home\') %]Home</a> |\n[%\\ this.a(\'/sample/AnotherValue\') %]Another Sample</a> |\n[%\\ this.a(\'specialOffer\') %]Special Offer</a>'
            })
        }
    }
    
})