Class('DemoApp.Widget.Sample', {
    
    xtype   : 'demoapp-widget-sample',
    
    isa : 'Symbie.Widget.Container',
    
    use : [ 'ExtX.Layout.Center', 'SymbieX.Template.Shotenjin.Container' ],
    
    
    has : {
        slots       : true,
        
        sampleValue : null
    },

    
    before : {
        
        initComponent : function () {
            
            Ext.apply(this, {
                
                layout : 'center',
                
                items : [
                    {
                        xtype : 'SymbieX.Template.Shotenjin.Container',
                        slot : 'centered',
                        
                        cls : 'demoapp-widget-sample-body',
                        
                        width : 500,
                        height : 330,
                        
                        templateData : {
                            value : this.sampleValue
                        },
                        
                        templateSources : {
                            /*tj
                                This is a Sample widget, it just translates passed value:<br>
                                <p class="demoapp-big">
                                    [% value %]
                                </p>
                            tj*/

                            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                            sources : 'This is a Sample widget, it just translates passed value:<br>\n<p class="demoapp-big">\n[% value %]\n</p>'
                        }

                    }                        
                ]
            })
        }
        //eof initComponent
    },
    
    
    methods : {
        
        touch : function (context, step) {
            var params = context.getParams()
            
            if (params.value) this.slots.centered.refresh({ value : params.value })
        }
    }
    
})