Class('DemoApp.Widget.SpecialOffer', {
    
    xtype   : 'demoapp-widget-specialoffer',
    
    isa : 'Symbie.Widget.Container',
    
    use : 'DemoApp.Template.Base',
    
    
    has : {
        slots       : true,
        
        template    : function () {
            return new DemoApp.Template.Base({
                /*tj

                    This is a Special Offer widget

                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : 'This is a Special Offer widget'
            })
        }
    },

    
    
    after : {
        
        onRender : function () {
            this.el.update(this.template.render())
        }
        
    }
    
})